### ISSUE TITLE
feature request: 希望增加根据tracker状态（是否working）打标签的功能

### ISSUE THREAD

**Issue by Imgaojp** [fengqi/qbittorrent-tool#1]
有些电视剧在播出时会单集更新，但是当整季播出后会将单集的种子ban掉，发一个打包版。由于目前没有很好的办法区分哪些已经被删掉了，所以积压了一些被ban的种子。如果可以根据tracker状态定期打标签可以更方便的筛选被ban种子。

**Comment by fengqi** [comment]
其实我一直也有这个困扰，之前一直懒得动手😂，这次我找时间加上

**Comment by fengqi** [comment]
看了下api，qb的状态只有0-4

种子删除、被墙网络不通、passkey不正确、禁止下载等其实都是状态4，qb tracker的消息那里可能会显示具体的信息，但是那个信息不是通用的，每个站点的值可能都不一样，因为是可以自定义的

0只有没关闭dht pex这些才会出现，状态都是0
1基本上只有刚添加的种子还没开始下载才会有
2是正常的
3只是临时的

**Comment by fengqi** [comment]
加上了

**Comment by Imgaojp** [comment]
多谢，你的效率太高了，bro。

**Comment by fengqi** [comment]
可以看下是不是你想要的样子，我目前是新增了一个针对性错误信息设置对应tag的配置，暂时还没想到别的方案。

**Comment by Imgaojp** [comment]
测试了一下，通过message可以映射到对应的TAG了 👍🏻
<img width="1564" alt="Screenshot 2023-09-01 at 01 06 21" src="https://github.com/fengqi/qbittorrent-tool/assets/6065749/7c47c0d4-4ec5-400d-88f3-9194a4dd93e7">
